packaging_format = 2

id = "contact-cnt-ait"
name = "Contacts Libres CNT-AIT"
description.en = "Decentralized contact management application for CNT-AIT"
description.fr = "Application décentralisée de gestion de contacts pour la CNT-AIT"

version = "1.4~ynh1"

maintainers = ["CNT-AIT"]

[upstream]
license = "GPL-3.0"
website = "https://github.com/Jesusiunchatnoir/contact-cnt-ait"
code = "https://github.com/Jesusiunchatnoir/contact-cnt-ait"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "1000M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/contacts"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "curl"