# GitHub Pages configuration for Liberchat Marketplace

# Site settings
title: "Liberchat Marketplace"
description: "Marketplace communautaire d'applications YunoHost avec validation automatique"
url: "https://liberchat.github.io"
baseurl: "/LiberChat-Marketplace"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files
exclude:
  - README.md
  - LICENSE
  - scripts/
  - apps/
  - .github/
  - .gitignore

# Include files
include:
  - _pages

# Collections
collections:
  apps:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# SEO
lang: fr
author: "Liberchat Community"

# Social
github_username: Liberchat
repository: "Liberchat/LiberChat-Marketplace"