#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
admin=$(ynh_app_setting_get --app=$app --key=admin)
port=$(ynh_app_setting_get --app=$app --key=port)

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_script_progression --message="Restoring the app main directory..." --weight=1
ynh_restore_file --origin_path="$install_dir"

chmod 750 "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================

ynh_script_progression --message="Restoring the data directory..." --weight=1
ynh_restore_file --origin_path="$data_dir" --not_mandatory

mkdir -p $data_dir
chown -R $app:www-data "$data_dir"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

ynh_script_progression --message="Recreating the dedicated system user..." --weight=1
ynh_system_user_create --username=$app --home_dir="$install_dir"

#=================================================
# RESTORE USER RIGHTS
#=================================================

chown -R $app:www-data "$install_dir"

#=================================================
# REINSTALL DEPENDENCIES
#=================================================

ynh_script_progression --message="Reinstalling dependencies..." --weight=1
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=18

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_script_progression --message="Restoring the NGINX web server configuration..." --weight=1
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE SYSTEMD CONFIGURATION
#=================================================

ynh_script_progression --message="Restoring the systemd configuration..." --weight=1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

#=================================================
# RESTORE LOGROTATE
#=================================================

ynh_script_progression --message="Restoring the logrotate configuration..." --weight=1
ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app --description="Contacts Libres CNT-AIT" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression --message="Starting a systemd service..." --weight=1
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX
#=================================================

ynh_script_progression --message="Reloading NGINX web server..." --weight=1
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --weight=1